spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kozos
    username: progmatic
    password: progmatic
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      port: 35730
    restart:
      exclude: templates/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 300KB
      max-request-size: 10MB
output:
    ansi:
      enabled: ALWAYS
server:
  port: 8082
logging:
  level:
    web: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%15X{user}){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}'
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: tesztuser
    password: tesztpass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true